### ISSUE TITLE
I can not run a .class files generated by the Jasmin

### ISSUE THREAD

**Issue by Circiter** [davidar/jasmin#3]
The jasmin.jar, already included in the distribution, successfully generates .class files from provided examples. But however I do such a class-files do not show any signs of life... For example, when I run `java -jar jasmin.jar HelloWorld.j` the jasmin creates the file HelloWorld.class but whenever I execute it via `java HelloWorld.class` I only see `Error: Could not find or load main class HelloWorld.class`.

I'm really interested in this project. But at the same time I'm afraid that it's too late to use this tool, after all in the documentation there are dates like 1996, 2004, and now, well, now 2021. :) On top of that the Java is not my primary language (it is why I choose this project in the first place). Rewriting the project in, e.g., C is possible in theory but some of the .java files are over thousand lines of code so I hope to use this software as-is without porting it first.

Is it necessary to build the jasmin.jar from sources or it's enough to run the .jar file already present there?

I'm testing the Jasmin on a relatively old Linux-box running the Slackware with Java version 1.7, JRE IcedTea7 2.3.3. The Jasmin was downloaded directly from davidar/jasmin at GitHub.

[Sorry for my poor English... :) ]

**Comment by roscopeco** [comment]
Hi!

I just tested this locally, and it works fine (using `HelloWorld` example from the README). To make it work, you need to change the `java` command you use to run the class - Java does not support passing in a class file as an argument. Instead, you need to set the class-path and pass in the name of the class:

```
java -cp . HelloWorld
```

For completeness, here's a complete run with the latest LTS release of Java:

```
➜  jasmin git:(master) java --version
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
➜  jasmin git:(master) java -jar jasmin.jar HelloWorld.j
Generated: HelloWorld.class
➜  jasmin git:(master) java -cp . HelloWorld
Hello World!
```

Please reply here (and close this) if this solves your issue. If not, I'll look further into it.

**Comment by Circiter** [comment]
Thank you very much. It works, how simple... :)

It's definitely worth to include a line such as "java -cp . <class_name>" into the documentation (either docs/guide.html or README.md). For, it silently assumes now that a typical user does know this java quirk, but no -- it's not obvious at all and nowhere in the documentation does it show such a invocation syntax (or I fail to find it).

But I will not make a pull request because now I see that apart from the README.md there is the Readme.txt in which I found a working instruction, citation: "You can then run the HelloWorld program by doin java examples.HelloWorld"; it differs significantly from the solution provided by you, yet it works too. (May be it's time to synchronize/merge README.md and Readme.txt, who knows...)

Thanks again for your answer.
