### ISSUE TITLE
Incomplete HelloWorld.j example

### ISSUE THREAD

**Issue by akorb** [davidar/jasmin#4]
The example at `https://github.com/davidar/jasmin/blob/master/examples/HelloWorld.j` seems to be incomplete. At least I wouldn't be able to derive from the source code why it should print "Hello World!". It also doesn't work when I run it.

```
$ java -cp . HelloWorld
Error: Unable to initialize main class HelloWorld
Caused by: java.lang.VerifyError: (class: HelloWorld, method: main signature: ([Ljava/lang/String;)V) Expecting to find object/array on stack
```

**Comment by roscopeco** [comment]
Thanks for reporting, fixed by merging https://github.com/davidar/jasmin/pull/2 👍
